/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_alejandrocardona;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jets
 */
public class MainUI extends javax.swing.JFrame {
    static Color color;
    static ArrayList<Vehiculo> vehiculos= new ArrayList();
    static ArrayList<Vendedor> vendedores = new ArrayList();
    static ArrayList<Cliente> clientes = new ArrayList();
    static File carros = null;
    FileWriter fw = null;
    BufferedWriter bw = null;

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        VehiculoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_Marca = new javax.swing.JTextField();
        TF_Modelo = new javax.swing.JTextField();
        TF_FechaVehiculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnColor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TF_PrecioVehiculo = new javax.swing.JTextField();
        VehiculoCrearBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TF_NombreVendedor = new javax.swing.JTextField();
        Btn_Vendedor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ClienteSpinner = new javax.swing.JSpinner();
        TF_NombreCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TF_Profesion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TF_SueldoDisponible = new javax.swing.JTextField();
        Btn_CrearCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        CB_Vendedor = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CB_Cliente = new javax.swing.JComboBox<>();
        CB_Vehiculo = new javax.swing.JComboBox<>();
        Btn_CrearArchivo = new javax.swing.JButton();
        Btn_GuardarArchivo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setText("Ingrese la Marca del Vehiculo");

        TF_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_MarcaActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese el Modelo del Vehiculo");

        jLabel4.setText("Año del Vehiculo");

        BtnColor.setText("Color");
        BtnColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnColorMouseClicked(evt);
            }
        });

        jLabel5.setText("Precio de Venta");

        TF_PrecioVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PrecioVehiculoActionPerformed(evt);
            }
        });

        VehiculoCrearBtn.setText("Crear Vehiculo");
        VehiculoCrearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VehiculoCrearBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VehiculoPanelLayout = new javax.swing.GroupLayout(VehiculoPanel);
        VehiculoPanel.setLayout(VehiculoPanelLayout);
        VehiculoPanelLayout.setHorizontalGroup(
            VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiculoPanelLayout.createSequentialGroup()
                .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehiculoPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(VehiculoPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(45, 45, 45)
                                    .addComponent(TF_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(VehiculoPanelLayout.createSequentialGroup()
                                    .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehiculoPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(117, 117, 117))
                                        .addGroup(VehiculoPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(45, 45, 45)))
                                    .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TF_FechaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                        .addComponent(TF_PrecioVehiculo))))
                            .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BtnColor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(VehiculoPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(48, 48, 48)
                                    .addComponent(TF_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(VehiculoPanelLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(VehiculoCrearBtn)))
                .addContainerGap())
        );
        VehiculoPanelLayout.setVerticalGroup(
            VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiculoPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(BtnColor)
                .addGap(68, 68, 68)
                .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(61, 61, 61)
                .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_FechaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(55, 55, 55)
                .addGroup(VehiculoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(TF_PrecioVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(VehiculoCrearBtn)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Vehiculo", VehiculoPanel);

        jLabel2.setText("Nombre del Vendedor");

        Btn_Vendedor.setText("Crear Vendedor");
        Btn_Vendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_VendedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn_Vendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(130, 130, 130)
                .addComponent(TF_NombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(517, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_NombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(Btn_Vendedor)
                .addContainerGap(511, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Vendedor", jPanel2);

        jLabel6.setText("Nombre del Cliente");

        jLabel7.setText("Edad del Cliente");

        jLabel8.setText("Profesion");

        jLabel9.setText("Sueldo Disponible");

        Btn_CrearCliente.setText("Crear Cliente");
        Btn_CrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CrearClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_CrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ClienteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_NombreCliente)
                            .addComponent(TF_Profesion)
                            .addComponent(TF_SueldoDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))))
                .addContainerGap(682, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TF_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ClienteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TF_Profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TF_SueldoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(Btn_CrearCliente)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Cliente", jPanel3);

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel10.setText("Vendedor");

        CB_Vendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Cliente");

        jLabel12.setText("Vehiculo");

        CB_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CB_Vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Btn_CrearArchivo.setText("Crear Archivo");
        Btn_CrearArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CrearArchivoMouseClicked(evt);
            }
        });

        Btn_GuardarArchivo.setText("Guardar Archivo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Btn_CrearArchivo)
                        .addGap(146, 146, 146)
                        .addComponent(Btn_GuardarArchivo))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CB_Vendedor, 0, 316, Short.MAX_VALUE)
                            .addComponent(CB_Cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_Vehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(653, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CB_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CB_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CB_Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_CrearArchivo)
                    .addComponent(Btn_GuardarArchivo))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Realizar Venta", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1268, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar JSONs", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnColorMouseClicked
        // TODO add your handling code here:
        
        color = JColorChooser.showDialog(VehiculoPanel,"Seleccione el Color del Vehiculo a Crear", Color.blue);
        
    }//GEN-LAST:event_BtnColorMouseClicked

    private void TF_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_MarcaActionPerformed

    private void TF_PrecioVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PrecioVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PrecioVehiculoActionPerformed

    private void VehiculoCrearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehiculoCrearBtnMouseClicked
        // TODO add your handling code here:
        
        String marca = TF_Marca.getText();
        String modelo = TF_Modelo.getText();
        int fecha = Integer.parseInt(TF_FechaVehiculo.getText());
        Double precio = Double.parseDouble(TF_PrecioVehiculo.getText());
        Vehiculo Carro = new Vehiculo(marca, modelo, color, fecha, precio);
        vehiculos.add(Carro);
        
        TF_Marca.setText("");
        TF_Modelo.setText("");
        TF_FechaVehiculo.setText("");
        TF_PrecioVehiculo.setText("");
        
        
        
        
        
        try {
            
            
            fw = new FileWriter(carros, true);
            bw = new BufferedWriter(fw);
            bw.write(Carro.toString());
            
            bw.flush();
        } catch (Exception e) {
            
            System.out.println(e.getStackTrace());
            
        }
        
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(VehiculoPanel, "El Vehiculo ha sido creado Exitosamente");
        
    }//GEN-LAST:event_VehiculoCrearBtnMouseClicked

    private void Btn_VendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_VendedorMouseClicked
        // TODO add your handling code here:
        
        File Vendedores = new File ("./Vendedores");
        FileWriter fwv = null;
        BufferedWriter bwv = null;
        
        String nombre = TF_NombreVendedor.getText();
        Vendedor v = new Vendedor(nombre);
        vendedores.add(v);
        
        TF_NombreVendedor.setText("");
        
        try {
            
            fwv = new FileWriter(Vendedores, true);
            bwv = new BufferedWriter(fwv);
            bwv.write(v.toString());
            bwv.flush();
            
        } catch (Exception e) {
        
            
            
        }
        
        try {
            
            bwv.close();
            fwv.close();
            
        } catch (Exception e) {
            
            System.out.println(e.getStackTrace());
            
        }
        JOptionPane.showMessageDialog(this, "Se ha creado un vendedor de manera exitosa");
        
        
    }//GEN-LAST:event_Btn_VendedorMouseClicked

    private void Btn_CrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CrearClienteMouseClicked
        // TODO add your handling code here:
        
        String nombre = TF_NombreCliente.getText();
        String profesion = TF_Profesion.getText();
        int edad = (Integer)ClienteSpinner.getValue();
        Double sueldo = Double.parseDouble(TF_SueldoDisponible.getText());
        Cliente c = new Cliente(nombre, profesion, sueldo, edad);
        clientes.add(c);
        
        TF_NombreCliente.setText("");
        TF_Profesion.setText("");
        TF_SueldoDisponible.setText("");
        
        File clients = new File ("./Clientes");
        FileWriter fwc = null;
        BufferedWriter bwc = null;
        
        try {
            
            fwc = new FileWriter (clients, true);
            bwc = new BufferedWriter(fwc);
            bwc.write(c.toString());
            bwc.flush();
            
        } catch (Exception e) {
        
            System.out.println(e.getStackTrace());
            
        }
        JOptionPane.showMessageDialog(this, "Se ha creado un cliente de manera exitosa");
        
        
    }//GEN-LAST:event_Btn_CrearClienteMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        
        cbVendedor();
        cbCliente();
        cbVehiculo();
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void Btn_CrearArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CrearArchivoMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_Btn_CrearArchivoMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        carros = new File("./Vehiculos");
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
        
    }

    
    private void cbVendedor(){
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)CB_Vendedor.getModel();
        modelo.removeAllElements();
        
        File vendedoresA = null;
        
        
        
        try {
            
            vendedoresA = new File("./Vendedores");
            String vendedoresT = "";
            Scanner read = new Scanner(vendedoresA);
            while(read.hasNext()){
                
                vendedoresT+= read.next();
            
            }
            
            String [] vendedoresArray = vendedoresT.split("]");
           
            String [] tokens;
            for (int i = 0; i < vendedoresArray.length; i++) {
                
                tokens = vendedoresArray[i].split(",");
                for (int j = 0; j < tokens.length; j++) {
                    
                    if(j == 0){
                        String pez = "";
                        for (int k = 1; k < tokens[j].length(); k++) {
                            
                            pez+=tokens[j].charAt(k);
                            
                        }
                        
                        modelo.addElement(pez);
                        
                    }
                    
                }
                
            }
            
            
            
            
            
            
            
        } catch (Exception e) {
        
            System.out.println(e.getMessage());
            
        }
        
        CB_Vendedor.setModel(modelo);
        
        
        
    }
    
    private void cbVehiculo(){
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)CB_Vehiculo.getModel();
        modelo.removeAllElements();
        
        File VehiculosA = null;
        
        
        
        try {
            
            VehiculosA = new File("./Vehiculos");
            String vehiculosT = "";
            Scanner read = new Scanner(VehiculosA);
            while(read.hasNext()){
                
                vehiculosT+= read.next();
            
            }
            
            String [] vehiculosArray = vehiculosT.split("]");
           
            String [] tokens;
            for (int i = 0; i < vehiculosArray.length; i++) {
                
                tokens = vehiculosArray[i].split(";");
                for (int j = 0; j < tokens.length; j++) {
                    
                    if(j == 0){
                        String pez = "";
                        for (int k = 1; k < tokens[j].length(); k++) {
                            
                            pez+=tokens[j].charAt(k);
                            
                        }
                        
                        modelo.addElement(pez);
                        
                    }
                    
                }
                
            }    
            
        } catch (Exception e) {
        
            System.out.println(e.getMessage());
            
        }
        
        
        CB_Vehiculo.setModel(modelo);
        
    }
    private void cbCliente(){
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)CB_Cliente.getModel();
        modelo.removeAllElements();
        
        File clientesA = null;
        
        
        
        try {
            
            clientesA = new File("./Clientes");
            String clientesT = "";
            Scanner read = new Scanner(clientesA);
            while(read.hasNext()){
                
                clientesT+= read.next();
            
            }
            
            String [] clientesArray = clientesT.split("]");
           
            String [] tokens;
            for (int i = 0; i < clientesArray.length; i++) {
                
                tokens = clientesArray[i].split(",");
                
                for (int j = 0; j < tokens.length; j++) {
                    
                    if(j == 0){
                        
                        String pez = "";
                        for (int k = 1; k < tokens[j].length(); k++) {
                            
                            pez+=tokens[j].charAt(k);
                            
                        }
                        
                        modelo.addElement(pez);
                        
                    }
                    
                }
                
            }
            read.close();
            
            
            
            
            
            
        } catch (Exception e) {
        
            System.out.println(e.getStackTrace());
            
        }
        
        CB_Cliente.setModel(modelo);
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnColor;
    private javax.swing.JButton Btn_CrearArchivo;
    private javax.swing.JButton Btn_CrearCliente;
    private javax.swing.JButton Btn_GuardarArchivo;
    private javax.swing.JButton Btn_Vendedor;
    private javax.swing.JComboBox<String> CB_Cliente;
    private javax.swing.JComboBox<String> CB_Vehiculo;
    private javax.swing.JComboBox<String> CB_Vendedor;
    private javax.swing.JSpinner ClienteSpinner;
    private javax.swing.JTextField TF_FechaVehiculo;
    private javax.swing.JTextField TF_Marca;
    private javax.swing.JTextField TF_Modelo;
    private javax.swing.JTextField TF_NombreCliente;
    private javax.swing.JTextField TF_NombreVendedor;
    private javax.swing.JTextField TF_PrecioVehiculo;
    private javax.swing.JTextField TF_Profesion;
    private javax.swing.JTextField TF_SueldoDisponible;
    private javax.swing.JButton VehiculoCrearBtn;
    private javax.swing.JPanel VehiculoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
